name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install npm
      run: npm install
    - name: Check lint
      run: npm run lint
